import type { Actor } from '@/contracts/auth';
import type { CursorPage } from '@/contracts/api';
import type { ClientOrderDTO, DashboardDTO, OrderQuery } from '@/contracts/orders';
import { db } from '@/server/db';

export class OrderNotFoundError extends Error { readonly status=404; }

function map(order:any):ClientOrderDTO { return {id:order.id,number:order.number,sidemark:order.sidemark,status:order.status,revision:order.revision,submittedAt:order.submittedAt.toISOString(),items:order.items.map((x:any)=>({...x,id:x.id,snapsSuggested:x.snapsSuggested,snapsSource:x.snapsSource,ruleVersion:x.ruleVersion})),specialNotes:order.specialNotes,attachments:[],publishedQuote:null}; }
function cursor(value?:string){if(!value)return undefined;const i=value.lastIndexOf(':');const date=new Date(value.slice(0,i));if(i<0||Number.isNaN(+date))throw new OrderNotFoundError();return{date,id:value.slice(i+1)};}
export async function listOrders(actor:Actor,query:OrderQuery):Promise<CursorPage<ClientOrderDTO>>{const c=cursor(query.cursor);const rows=await db.order.findMany({where:{organizationId:actor.organizationId,...(query.status?{status:query.status}:{}),...(query.q?{OR:[{number:{contains:query.q,mode:'insensitive'}},{sidemark:{contains:query.q,mode:'insensitive'}}]}:{}),...(c?{OR:[{submittedAt:{lt:c.date}},{submittedAt:c.date,id:{lt:c.id}}]}:{})},include:{items:true},orderBy:[{submittedAt:'desc'},{id:'desc'}],take:query.limit+1});const next=rows[query.limit];return{data:rows.slice(0,query.limit).map(map),page:{nextCursor:next?`${next.submittedAt.toISOString()}:${next.id}`:null},requestId:''};}
export async function getOrder(actor:Actor,id:string){const row=await db.order.findFirst({where:{id,organizationId:actor.organizationId},include:{items:true}});if(!row)throw new OrderNotFoundError();return map(row);}
export async function getDashboard(actor:Actor):Promise<DashboardDTO>{const [orders,draft]=await Promise.all([db.order.findMany({where:{organizationId:actor.organizationId},include:{items:true},orderBy:{submittedAt:'desc'},take:5}),db.draft.findFirst({where:{userId:actor.userId,organizationId:actor.organizationId}})]);return{counts:{total:orders.length,received:orders.filter(x=>x.status==='received').length,inProduction:orders.filter(x=>x.status==='in_production').length,completed:orders.filter(x=>x.status==='delivered').length},completedDefinition:'delivered-provisional',recentOrders:orders.map(map),draft:draft?{id:draft.id,revision:draft.revision,modelCount:Array.isArray((draft.payload as any).items)?(draft.payload as any).items.length:0}:null};}
